language: php

php:
  - 5.5
  - 5.6

services:
  - mongodb

env:
  global:
    - PHALCON_VERSION="phalcon-v2.0.8"
    - PATH="$PATH:~/bin"

before_script:
  - phpenv config-add travis/php.ini
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - cp tests/fixtures/app/config/config.sample.php tests/fixtures/app/config/config.php
  - mkdir -p tests/fixtures/cache
  - mkdir -p tests/fixtures/tmp
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - coveralls